### ISSUE TITLE
关于预训练模型

### ISSUE THREAD

**Issue by godjiawen** [bubbliiiing/efficientnet-yolo3-pytorch#11]
up主的 yolo3-efficientnet-b0-voc.pth是自己训练的吗？还是从哪里找的。

**Comment by godjiawen** [comment]
是从0开始在imagenet上训练得到的吗？
感谢回复。

**Comment by bubbliiiing** [comment]
……目标检测啊…voc啊

**Comment by godjiawen** [comment]
好的好的，我以为这种预训练模型文件都需要在imagenet数据集上训练才能得到，抱歉。
